#!/bin/bash
cd /root
clear
sleep 1
echo -e "\033[35m 1.搭建加速\033[0m"
echo
echo -e "\033[35m 2.搭建多端口酸酸乳（by Toyo）\033[0m"
echo
echo -e "\033[35m 3.sspanel后端对接（by Toyo） \033[0m"
echo
echo -e "\033[35m 4.搭建v2ray基本版\033[0m"
echo
echo -e "\033[35m 5.搭建v2rayUI面板(无确认直接安装)\033[0m"
echo
echo -e "\033[35m 6.搭建v2ray功能完善版\033[0m"
echo
echo -e "\033[35m 7.搭建trojan\033[0m"
echo
echo -e "\033[35m 8.Superspeed测速（by oldking）\033[0m"
echo
echo -e "\033[35m 9.一键测试脚本bench（by Zench）\033[0m"
echo
echo -e "\033[35m 10.搭建GOST（by supppig）\033[0m"
echo
echo -e "\033[35m 11.sspanel前端+后端（by supppig）\033[0m"
echo
echo -e "\033[35m 12.WordPress+V2ray+Ws+Tls一键安装脚本，已集成破解主题：D8 5.1、DUX 6.0、Git主题！最时尚的科学上网方式！\033[0m"
echo
echo -e  "\033[35m 请选择 [ 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10, 11, 12 ] 进行下一步安装！\033[0m
 
 >请选择安装类型: "
read az
  case $az in
    1) wget -N --no-check-certificate "https://raw.githubusercontent.com/1400002030/xiaohei/master/tcp.sh" && chmod +x tcp.sh && ./tcp.sh
       ;;
    2) wget -q https://raw.githubusercontent.com/1400002030/xiaohei/master/ssr && bash ssr
       ;;
    3) yum -y install wget &&
wget -N --no-check-certificate https://raw.githubusercontent.com/lizhongnian/ss-panel-v3-mod-node-connect/master/ss-panel-v3-mod-node-connect.sh && 
chmod +x ss-panel-v3-mod-node-connect.sh && 
bash ss-panel-v3-mod-node-connect.sh 
       ;;
    4) cd ~;rm -rf v2ray.*;wget https://raw.githubusercontent.com/1400002030/xiaohei/master/v2ray.sh;chmod 777 v2ray.sh;./v2ray.sh 2>&1 | tee v2ray.log;rm -rf v2ray.sh && bash v2ray.sh
       ;;
   	5) wget -q https://raw.githubusercontent.com/1400002030/xiaohei/master/v2ray-ui.sh && bash v2ray-ui.sh
	   ;;
	6) wget -q https://raw.githubusercontent.com/1400002030/xiaohei/master/v2ray-pro.sh && bash v2ray-pro.sh
	   ;;
	7) wget -q https://raw.githubusercontent.com/1400002030/xiaohei/master/trojan.sh && bash trojan.sh
	   ;;
	8)  wget https://raw.githubusercontent.com/oj8k/oj8k/master/ces/superspeed.sh
chmod +x superspeed.sh
./superspeed.sh
	   ;;
   	9) wget https://raw.githubusercontent.com/oj8k/oj8k/master/ces/ZBench-CN.sh && bash ZBench-CN.sh
	   ;;
        10) wget https://raw.githubusercontent.com/oj8k/oj8k/master/gost/gost.sh && bash gost.sh
	   ;;
	11) wget https://raw.githubusercontent.com/1400002030/xiaohei/master/sspanel && bash sspanel
	    ;;
	12) yum install -y wget && wget https://raw.githubusercontent.com/1400002030/xiaohei/master/WP_V2ray_Ws_Tls.sh && chmod +x WP_V2ray_Ws_Tls.sh && ./WP_V2ray_Ws_Tls.sh
	    ;;
    *)  echo -e "\033[31m 错误：只能选择[ 1 , 2 , 3, 4 , 5 , 6 , 7 , 8 , 9 , 10 ]！！\033[0m"
       ;; 
  esac
